server:
  port: 8085

spring:
  application:
    name: api-gateway

  security:
    user:
      name: admin
      password: admin123

  cloud:
    gateway:
      # Enables automatic routing using Eureka service IDs
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Enable gateway metrics (IMPORTANT)
      metrics:
        enabled: true

      routes:
        - id: customer-api
          uri: lb://customer-api
          predicates:
            - Path=/api/customers/**
          filters:
            - RemoveRequestHeader=X-GATEWAY-KEY
            - AddRequestHeader=X-GATEWAY-KEY, ${gateway.secret}

        - id: customer-status-service
          uri: lb://customer-status-service
          predicates:
            - Path=/status/**
          filters:
            - RemoveRequestHeader=X-GATEWAY-KEY
            - AddRequestHeader=X-GATEWAY-KEY, ${gateway.secret}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

gateway:
  secret: 9f3a7c1d-very-secret-value

# =========================
# ACTUATOR (CRITICAL)
# =========================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true

logging:
  file:
    name: logs/api-gateway.log
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.reactive.DispatcherHandler: TRACE
    reactor.netty.http.client: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger - %msg%n"